### ISSUE TITLE
Improve Scheduler

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/orchard#7] opened 2023-01-26 17:47 UTC
Let's make the scheduling be aware of the available resources on the workers and schedule things accordingly.

IMO for a given VM the controller should find all suitable workers and than pick one randomly to assign a VM to worker.

**Comment by edigaryev** [comment] 2023-03-24 17:26
Duplicate of https://github.com/cirruslabs/orchard/issues/47.

**Closed as not planned by edigaryev** 2023-03-24 17:26 UTC
Labels: enhancement
