### ISSUE TITLE
Option to pause a worker

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/orchard#5] opened 2023-01-26 17:44 UTC
Similar to how we do for Cirrus CI's persistent worker, let's make an option on the worker side to pause itself and wait for all VMs to drain. This is useful for rolling updates of the workers.

**Comment by edigaryev** [comment] 2023-03-23 14:41
Duplicate of https://github.com/cirruslabs/orchard/issues/45.

**Closed as not planned by edigaryev** 2023-03-23 14:41 UTC
