### ISSUE TITLE
`orchard ssh vm <id>` may yield `Error #01: store entry not found`

### ISSUE THREAD

**Issue by ruimarinho** [cirruslabs/orchard#97] opened 2023-06-29 11:15 UTC
If `orchard ssh vm <id>` is called for a VM identifier that doesn't exist, the client hangs and the controller logs the following message:

```
controller-0 controller [GIN] 2023/06/29 - 11:12:27 | 404 |     124.343µs |  10.10.10.100 | GET      "/v1/vms/29dfa34f-b8b4-47de-a1f1-a465984c079c/port-forward?port=22&wait=60"
controller-0 controller Error #01: store entry not found
```

Client:

```
orchard ssh vm 29dfa34f-b8b4-47de-a1f1-a465984c079c
failed to forward an SSH port to VM 29dfa34f-b8b4-47de-a1f1-a465984c079c: websocket.Dial wss://orchard.example.internal:443/v1/vms/29dfa34f-b8b4-47de-a1f1-a465984c079c/port-forward?port=22&wait=60: bad status
2023/06/29 12:13:11 websocket.Dial wss://orchard.example.internal:443/v1/vms/29dfa34f-b8b4-47de-a1f1-a465984c079c/port-forward?port=22&wait=60: bad status
```

**Comment by edigaryev** [comment] 2023-07-04 12:50
I've addressed the weird errors in https://github.com/cirruslabs/orchard/pull/105.

Regarding the "client hangs" — does this reproduce when running Orchard locally? Unfortunately it doesn't for me, but you might check if will get improved after this PR is merged and released because we switched to the new WebSocket implementation.

**Closed** 2023-07-04 14:10 UTC
